### PR TITLE
linux: sometimes <limits.h> does not define PATH_MAX

### PR DESCRIPTION
**Pull request by jcelerier**

### CODE REVIEW

**Comment by gpakosz** [comment]
Hello @jcelerier 👋

What do you think of
```
#if defined(__linux__)
#include <linux/limits.h>
#else
#include <limits.h>
#endif
```

instead?

**Comment by jcelerier** [comment]
hi!  I'm not knowledgeable enough to tell if it will *always* be included in linux/limits.h (I would hope so though ! and it looks like it's the case : https://github.com/torvalds/linux/blob/master/include/uapi/linux/limits.h ).

**Comment by gpakosz** [comment]
On which Linux are you facing this btw?

**Comment by jcelerier** [comment]
On a raspberry pi, with raspbian.

**Comment by gpakosz** [comment]
Ok so it just doesn't compile right?

**Comment by jcelerier** [comment]
yup: 

```
whereami.c:183:15: error: ‘PATH_MAX’ was not declared in this scope
   char buffer[PATH_MAX];
               ^~~~~~~~
```

**Comment by jcelerier** [comment]
yup: 

```
whereami.c:183:15: error: ‘PATH_MAX’ was not declared in this scope
   char buffer[PATH_MAX];
               ^~~~~~~~
```

**Comment by gpakosz** [comment]
Can you please make you second commit a fixup of the first one? So that you have a single commit with a nice commit message? 🙏

**Comment by jcelerier** [comment]
I squashed them in a single commit.

**Comment by gpakosz** [comment]
Thanks for the PR 👍

**Comment by jcelerier** [comment]
thanks !

**Pull request merged**
