### PR TITLE
added support for SunOS

### PR DESCRIPTION
**Pull request by willtho89**
added support for SunOS (based on #11 )

### CODE REVIEW

**Comment by gpakosz** [comment]
Hi!

Can you also please rename the commit message? As far as I can tell you only renamed the PR. If you never did this, use `git rebase -i` and `reword`. Then force push your branch and the PR will catch up.

**Comment by willtho89** [comment]
Done.

**Comment by gpakosz** [comment]
Thanks for your contribution!

**Comment by gpakosz** [comment]
@Reldeis It doesn't look like it but I did merge your PR!

**Pull request closed without merging**
